name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pandas

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile app.py

      - name: Compress EXE into ZIP
        run: |
          powershell -Command "Compress-Archive -Path dist\app.exe -DestinationPath build_output\app.zip"

      - name: List ZIP output (for debugging)
        run: dir build_output

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-windows-app
        path: dist/tu_script.exe
