name: Build Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write  # Permite crear releases con GITHUB_TOKEN

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller pandas

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile app.py

      - name: Compress EXE into ZIP
        run: |
          powershell -Command "Compress-Archive -Path dist\app.exe -DestinationPath app.zip"

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          name: Build Release
          tag_name: v1.${{ github.run_number }}
          files: app.zip
