name: Build Windows EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller pandas

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile tu_script.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-windows-app
        path: dist/tu_script.exe
